export type LoginStep =
  | 'ROLE_CHOOSE'
  | 'OWNER_PHONE_LOGIN'
  | 'OWNER_OTP_VERIFY'
  | 'EMPLOYEE_METHOD'
  | 'EMPLOYEE_EMAIL_LOGIN'
  | 'EMPLOYEE_EMAIL_OTP'
  | 'EMPLOYEE_CREDENTIALS'
  | 'SUCCESS'
